version: "3.7"

services:
  caddy:
    restart: "no"
    image: caddy:2.6
    ports:
      # - "80:80"
      # - "443:443"
      - "8899:8899"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./volume/caddy/data:/data
      - ./volume/caddy/config:/config
      - ./volume/caddy/storage:/etc/caddy/storage
      - ./volume/www:/www

  backend:
    restart: "no"
    build:
      context: ./src/backend/
      args:
        CHINA_WORKAROUND: "false"
    volumes:
      - ./volume/www:/www
    environment:
      - OPENAI_KEY=YOUR_API_KEY_HERE
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DJANGO_SUPERUSER_PASSWORD=123456

  frontend:
    restart: "no"
    build:
      context: ./src/frontend/
      args:
        CHINA_WORKAROUND: "false"
    volumes:
      - ./volume/www:/www
